# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'map (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'CocoaMQTT'  
  # Pods for map (iOS)

end

target 'map (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for map (macOS)

end
